name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EmployeeManager.Server/EmployeeManager.Server.sln

      - name: Build
        run: dotnet build --no-restore EmployeeManager.Server/EmployeeManager.Server.sln

      - name: Test
        run: dotnet test --no-build --verbosity normal EmployeeManager.Server/EmployeeManager.Server.sln 